# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main  # ou master, dependendo do seu branch

pool:
  name: Default
  demands:
    - Agent.Name -equals Agente-Local
    
variables:
  imageName: 'Cap7'        # nome da imagem
  tag: '$(Build.BuildId)'    # tag única por build

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build e Push da imagem Docker'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'ACR-Thot-Registry'  # nome configurado no Azure DevOps
    repository: '$(imageName)'
    dockerfile: 'API/Dockerfile'
    buildContext: '.'
    tags: |
      $(tag)
      latest
